# Generated by Django 4.2 on 2023-08-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0027_alter_variablevalues_recordedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModBusService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='modbus service name')),
                ('method', models.IntegerField(choices=[('rtu', 'RTU'), ('tcp', 'TCP/IP')], verbose_name='Mode du protocole')),
                ('rtu_slave_addesse', models.IntegerField(blank=True, verbose_name="Adresse de l'eclave en mode RTU")),
                ('port_or_address', models.CharField(max_length=50, verbose_name='Adresse du peripherique (TCP/IP) ou port (RTU)')),
                ('active', models.BooleanField(default=True)),
                ('baudrate', models.IntegerField(default=9600, verbose_name='Vitesse en baude')),
                ('stopbits', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Nombre de bits de stop')),
                ('bytesize', models.IntegerField(choices=[(8, '8'), (7, '7')], default=8, verbose_name='Vitesse en baude')),
                ('number_register_to_read', models.IntegerField(verbose_name='Nombre de registre à lire')),
                ('timeout', models.IntegerField(default=1, verbose_name='Configuration du timeout en seconde')),
                ('server_port', models.IntegerField(blank=True, verbose_name='Port du serveur dans le cas du TCP/IP')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.device', verbose_name='Peripherique associé au service')),
            ],
        ),
    ]
