# Generated by Django 4.2 on 2023-08-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_chart_charttype'),
        ('webService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.device'),
        ),
    ]
