# Generated by Django 4.2 on 2023-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0002_webservice_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='path',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Path of variable name response'),
        ),
    ]
