# Generated by Django 4.2 on 2023-08-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0003_webservice_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='contentType',
            field=models.IntegerField(choices=[(0, 'JSON'), (1, 'XML')], default=0, verbose_name='Content of device response'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='method',
            field=models.IntegerField(choices=[(0, 'Path'), (1, 'GET')], default=0, verbose_name='Method to get data'),
        ),
    ]
