# Generated by Django 4.2 on 2023-08-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0004_alter_webservice_contenttype_alter_webservice_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webservice',
            name='device',
        ),
    ]
