# Generated by Django 4.2.3 on 2023-08-02 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Alert Variable Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description of alert')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Chart name')),
                ('legende_axe_x', models.CharField(default='axe X', max_length=100, verbose_name='Legende X')),
                ('legende_axe_y', models.CharField(default='axe Y', max_length=100, verbose_name='Legende X')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateField()),
                ('widht', models.CharField(choices=[('25%', '25%'), ('33%', '33%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='100%', max_length=10)),
                ('position', models.IntegerField(verbose_name='Position in the list')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=80, verbose_name='variable name')),
                ('R', models.PositiveSmallIntegerField(default=0)),
                ('G', models.PositiveSmallIntegerField(default=0)),
                ('B', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='Device name')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Device description')),
                ('active', models.BooleanField(default=True)),
                ('byte_order', models.CharField(choices=[('1-0-3-2', '1-0-3-2'), ('0-1-2-3', '0-1-2-3'), ('2-3-0-1', '2-3-0-1'), ('3-2-1-0', '3-2-1-0')], default='1-0-3-2', max_length=15)),
                ('polling_interval', models.FloatField(choices=[(0.1, '100 Milliseconds'), (0.5, '500 Milliseconds'), (1.0, '1 Second'), (5.0, '5 Seconds'), (10.0, '10 Seconds'), (15.0, '15 Seconds'), (30.0, '30 Seconds'), (60.0, '1 Minute'), (150.0, '2.5 Mintues'), (300.0, '5 Minutes'), (360.0, '6 Minutes (10 times per Hour)'), (600.0, '10 Minutes'), (900.0, '15 Minutes'), (1800.0, '30 Minutes'), (3600.0, '1 Hour'), (21600.0, '6 Hours'), (43200.0, '12 Hours'), (86400.0, '1 Day'), (604800.0, '1 Week')], default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProtocol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[(0, 'Web Service'), (1, 'Modbus'), (2, 'BacNet')], max_length=400)),
                ('description', models.TextField(default='', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Scaling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('input_low', models.FloatField()),
                ('input_high', models.FloatField()),
                ('output_low', models.FloatField()),
                ('output_high', models.FloatField()),
                ('limit_input', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=80, verbose_name='Unit')),
                ('description', models.TextField(default='', null=True, verbose_name='Description')),
                ('udunit', models.CharField(default='', max_length=500, verbose_name='udUnit')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=200, unique=True, verbose_name='variable name')),
                ('description', models.TextField(default='', null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True)),
                ('writeable', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('value_class', models.CharField(choices=[('FLOAT32', 'REAL (FLOAT32)'), ('FLOAT32', 'SINGLE (FLOAT32)'), ('FLOAT32', 'FLOAT32'), ('UNIXTIMEF32', 'UNIXTIMEF32'), ('FLOAT64', 'LREAL (FLOAT64)'), ('FLOAT64', 'FLOAT  (FLOAT64)'), ('FLOAT64', 'DOUBLE (FLOAT64)'), ('FLOAT64', 'FLOAT64'), ('UNIXTIMEF64', 'UNIXTIMEF64'), ('FLOAT48', 'FLOAT48'), ('INT64', 'INT64'), ('UINT64', 'UINT64'), ('UNIXTIMEI64', 'UNIXTIMEI64'), ('INT48', 'INT48'), ('UNIXTIMEI32', 'UNIXTIMEI32'), ('INT32', 'INT32'), ('UINT32', 'DWORD (UINT32)'), ('UINT32', 'UINT32'), ('INT16', 'INT (INT16)'), ('INT16', 'INT16'), ('UINT16', 'WORD (UINT16)'), ('UINT16', 'UINT (UINT16)'), ('UINT16', 'UINT16'), ('INT8', 'INT8'), ('UINT8', 'UINT8'), ('BOOLEAN', 'BOOL (BOOLEAN)'), ('BOOLEAN', 'BOOLEAN')], default='FLOAT64', max_length=15, verbose_name='value_class')),
                ('cov_increment', models.FloatField(default=0, verbose_name='COV')),
                ('chart_line_thickness', models.PositiveSmallIntegerField(choices=[(3, '3Px')], default=3)),
                ('value_min', models.FloatField(blank=True, null=True)),
                ('value_max', models.FloatField(blank=True, null=True)),
                ('min_type', models.CharField(choices=[('lte', '<='), ('lt', '<')], default='lte', max_length=4)),
                ('max_type', models.CharField(choices=[('gte', '>='), ('gt', '>')], default='gte', max_length=4)),
                ('alerts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.alertvariable')),
                ('chart_line_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.color')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.device')),
                ('scaling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.scaling')),
                ('unit', models.ForeignKey(on_delete=models.SET(1), to='buildings.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Page name')),
                ('link_name', models.CharField(max_length=50, verbose_name='Link name')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('position', models.IntegerField(verbose_name='Position in the list')),
                ('visible', models.BooleanField(default=True)),
                ('charts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.chart')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buildings.deviceprotocol'),
        ),
        migrations.AddField(
            model_name='chart',
            name='devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buildings.device'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Building name')),
                ('address', models.CharField(max_length=200, verbose_name='Building address')),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('position', models.IntegerField(verbose_name='Position in the list')),
                ('visible', models.BooleanField(default=True)),
                ('pages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.page')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
