# Generated by Django 4.2 on 2023-08-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_rename_name_device_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertvariable',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description of alert'),
        ),
        migrations.AlterField(
            model_name='alertvariable',
            name='updatedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='pages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.page'),
        ),
        migrations.AlterField(
            model_name='building',
            name='updatedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='devices',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buildings.device'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='legende_axe_x',
            field=models.CharField(blank=True, default='axe X', max_length=100, verbose_name='Legende X'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='legende_axe_y',
            field=models.CharField(blank=True, default='axe Y', max_length=100, verbose_name='Legende X'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='updatedAt',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='widht',
            field=models.CharField(blank=True, choices=[('25%', '25%'), ('33%', '33%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='100%', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Device description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buildings.deviceprotocol'),
        ),
        migrations.AlterField(
            model_name='deviceprotocol',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='charts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.chart'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updatedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='alerts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.alertvariable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.device'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='updatedAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
