# Generated by Django 4.2 on 2023-08-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_alertvariable_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chartType',
            field=models.IntegerField(choices=[(0, 'BARS'), (1, 'LINES'), (2, 'DONUT'), (3, 'GAUGE'), (4, 'LOAD PROFIL')], default=0, null=True, verbose_name='Chart Type'),
        ),
    ]
