# Generated by Django 4.2 on 2023-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_alter_deviceprotocol_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address of this device'),
        ),
        migrations.AlterField(
            model_name='deviceprotocol',
            name='protocol',
            field=models.IntegerField(choices=[(0, 'Web Service'), (1, 'Modbus'), (2, 'BacNet')], verbose_name='Protocol'),
        ),
    ]
