# Generated by Django 4.2 on 2023-08-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_device_address_alter_deviceprotocol_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprotocol',
            name='protocol',
            field=models.CharField(choices=[('Web Service', 'Web Service'), ('Modbus', 'Modbus'), ('BacNet', 'BacNet')], max_length=20, verbose_name='Protocol'),
        ),
    ]
