# Generated by Django 4.2 on 2023-08-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_alter_deviceprotocol_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='devices',
        ),
        migrations.AddField(
            model_name='chart',
            name='varaibles',
            field=models.ManyToManyField(to='buildings.variable'),
        ),
    ]
