# Generated by Django 4.2 on 2023-08-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_remove_chart_devices_chart_varaibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='value',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
