# Generated by Django 4.2 on 2023-08-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_variable_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='varaibles',
            new_name='variables',
        ),
    ]
