# Generated by Django 4.2 on 2023-08-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_rename_varaibles_chart_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recordedAt', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(blank=True, editable=False, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='variable',
            name='value',
        ),
        migrations.AddField(
            model_name='variable',
            name='values',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.variablevalues'),
        ),
    ]
