# Generated by Django 4.2 on 2023-08-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_remove_variable_device_device_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='variables',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.variable'),
        ),
    ]
