# Generated by Django 4.2 on 2023-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_alter_variable_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='variables',
        ),
        migrations.AddField(
            model_name='device',
            name='variables',
            field=models.ManyToManyField(blank=True, null=True, to='buildings.variable'),
        ),
    ]
