# Generated by Django 4.2 on 2023-08-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0005_remove_webservice_device'),
        ('buildings', '0015_remove_device_variables_device_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='webService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webService.webservice'),
        ),
    ]
