# Generated by Django 4.2 on 2023-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_device_webservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='webService',
        ),
        migrations.AlterField(
            model_name='device',
            name='variables',
            field=models.ManyToManyField(blank=True, to='buildings.variable'),
        ),
    ]
