# Generated by Django 4.2 on 2023-08-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0005_remove_webservice_device'),
        ('buildings', '0017_remove_device_webservice_alter_device_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='webService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webService.webservice'),
        ),
    ]
