# Generated by Django 4.2.3 on 2023-08-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0019_rename_widht_chart_width_alter_chart_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='values',
        ),
        migrations.AddField(
            model_name='variablevalues',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.variable'),
        ),
    ]
