# Generated by Django 4.2.3 on 2023-08-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_remove_variable_values_variablevalues_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.variable'),
        ),
    ]
