# Generated by Django 4.2.3 on 2023-08-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_remove_building_pages_page_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
    ]
