# Generated by Django 4.2.3 on 2023-08-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_alter_page_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='updatedAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.variable'),
        ),
    ]
