# Generated by Django 4.2 on 2023-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0024_remove_page_charts_chart_pages_alter_page_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chartType',
            field=models.IntegerField(choices=[(0, 'BARS'), (1, 'LINES'), (2, 'DONUT'), (3, 'GAUGE'), (4, 'LOAD PROFIL'), (5, 'NUMBER')], default=0, null=True, verbose_name='Chart Type'),
        ),
    ]
