# Generated by Django 4.2 on 2023-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0026_alter_variablevalues_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablevalues',
            name='recordedAt',
            field=models.DateTimeField(),
        ),
    ]
